# Generated by Django 4.2 on 2023-04-05 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=15, null=True)),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('position', models.CharField(blank=True, choices=[('Gerente de tienda', 'Gerente de tienda'), ('Gerente de taller', 'Gerente de taller'), ('Gerente de venta', 'Gerente de venta'), ('Gerente general (CEO)', 'Gerente general (CEO)'), ('Ejecutivo de ventas', 'Ejecutivo de ventas'), ('Encargado de producción', 'Encargado de producción'), ('Encargado de corte', 'Encargado de corte'), ('Producción saco', 'Producción saco'), ('Producción pantalón', 'Producción pantalón'), ('Producción chaleco', 'Producción chaleco')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
